Improvement
christy313/vanilla-js-todo-list pull request #1
Opened 2022-07-16 01:54 UTC by christy313

2022-07-16 22:18 UTC, christy313 commented
Hi Jessie,

This is a todo-list made with HTML, CSS, and vanilla JavaScript. and it is stored in local storage.
There are add/delete/check todo functions, the improvement is to press enter key down to add todo instead of pressing an add button.

I haven't done the edit todo part.

Christy

2022-07-18 14:48 UTC, iamseye requested changes

2022-07-18 14:48 UTC, iamseye commented on Script.js
> +const addTodo = (todo) => {
naming, ex: `createTaskInnerHTML`

2022-07-18 14:48 UTC, iamseye commented on Script.js
> +  todosContainer.appendChild(todoDiv);
`todosContainer` is a global variable, can you return todoDiv and append outside of the function?

2022-07-18 14:48 UTC, iamseye commented on Script.js
> +    addTodo(todo);
`const newTaskInnerHTML = addTodo(todo)`
`todosContainer.appendChild(newTaskInnerHTML)`

2022-07-20 23:21 UTC, iamseye commented on index.js
> +let taskItems = JSON.parse(localStorage.getItem("taskItems")) || [];
can you rename it? `savedTaskitems`?

2022-07-20 23:21 UTC, iamseye commented on index.js
> +    taskItems.push(taskContent);
why do you have to update the savedTaksItems?

2022-07-20 23:21 UTC, iamseye commented on index.js
> +  completeTodo(taskId, checkBox, taskItems);
This will be `checkTask` / `toggleTask` or can only `completeTask`  ?

2022-07-20 23:22 UTC, iamseye commented on Style.css
>  * {
The file naming `style.css` for syncing with other file names

2022-07-22 00:06 UTC, christy313 commented on index.js
> +    taskItems.push(taskContent);
it needs to be pushed inside `savedTaskItems` to save in local storage

2022-07-22 00:09 UTC, christy313 commented on index.js
> +  completeTodo(taskId, checkBox, taskItems);
I changed the function name from `completeTodo` to `checkTodo` for check/uncheck a checkbox

2022-07-22 02:46 UTC, merged